LTPTDL2_Nguyễn Thị Hà Duyên_16036191

In [56]:
import pandas as pd

In [57]:
import numpy as np

In [58]:

import seaborn as sns

In [59]:
import matplotlib.pyplot as plt

In [62]:
df = pd.read_excel("/content/KQThiLyThuyet-26.12.2020_ca2.xls")

In [50]:
data=df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  66 non-null     object
 1   Unnamed: 1  68 non-null     object
 2   Unnamed: 2  65 non-null     object
 3   Unnamed: 3  67 non-null     object
 4   Unnamed: 4  67 non-null     object
 5   Unnamed: 5  61 non-null     object
 6   Unnamed: 6  67 non-null     object
 7   Unnamed: 7  65 non-null     object
dtypes: object(8)
memory usage: 5.4+ KB

In [46]:
df.head()

              Unnamed: 0 Unnamed: 1 Unnamed: 2  ... Unnamed: 5 Unnamed: 6 Unnamed: 7
0                    NaN        NaN        NaN  ...        NaN        NaN        NaN
1                    NaN        NaN        NaN  ...        NaN        NaN        NaN
2                    NaN        NaN        NaN  ...        NaN        NaN        NaN
3  KẾT QUẢ THI LÝ THUYẾT        NaN        NaN  ...        NaN        NaN        NaN
4                    NaN        NaN        NaN  ...        NaN        NaN        NaN

[5 rows x 8 columns]

In [55]:
print(df['Unnamed: 4'])

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
     ...
79    NaN
80    NaN
81    NaN
82    NaN
83    NaN
Name: Unnamed: 4, Length: 84, dtype: object